### ISSUE TITLE
Arrumar o arquivo de fonts.scss

### ISSUE THREAD

**Issue by RafaelLimaC** [devhatt/pet-dex-frontend#102]
**Describe the bug**
A short description of what the bug is.

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   As variáveis estão com nomes errados, valores incorretos, ausencia de valores e não estão seguindo o layout definido no figma.
   Esse arquivo quebra a página ao usar pnpm dev
</details>

<br>

<details> 
  <summary>
    <b>Steps to Reproduce</b>
  </summary>

  Basta usar o 'pnpm dev' e tentar abrir a home no navegador.

</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>
   A home page não vai renderizar porque o sidemenu usa o arquivo fonts e ele está quebrado.
</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>
  
![image](https://github.com/devhatt/pet-dex-frontend/assets/132157467/7591d9a9-f676-45dc-b2e7-df099a357cc1)

</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by RafaelLimaC** [comment]
Eu quero!!!
