### ISSUE TITLE
Corrigir os links de guidelines

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/pet-dex-frontend#104]
**Describe the bug**
Os links de guidelines na action de auto assign da issue apontam pra o lugar errado.

<details> 
  <summary>
    <b>Steps to Reproduce</b>
  </summary>

Quando uma pessoa comenta `Eu quero!!!` é executado uma action que da assign a pessoa que comentou e responde com os links de guidelines.

</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>
  Os links direcionando para as documentações corretas.
</details>

<br>

<details> 
  <summary>
    <b>Current Behavior</b>
  </summary>
  Os links direcionam para arquivos/locais que não existem.
</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>

  ![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/be213679-d55c-46c4-9ba0-5bf95765eb18)
  ![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/e099499f-6a88-410b-b5c8-837cbb01e14f)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  [Provide any additional information, such as relevant versions, browser, OS, context, etc.]

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
