### ISSUE TITLE
Tela de porte do Pet

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/pet-dex-frontend#107]
**Describe the feature**
Criação da tela de porte do pet.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Essa task tem o objetivo de criar a tela de seleção do porte do pet, correspondente a etapa 4 do cadastro de pet.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Eu como usuário poderei selecionar o porte do meu pet.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

**Atente-se que os componentes da tela devem retornar o dado atualizado através de um evento de `emitter` para o componente pai.**
O desenvolvedor deverá utilizar os componentes abaixo para criar esta tela e suas funcionalidades:
- [x] #24 
- [x] #23 
- [x] #65 

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/ec0f1ca4-b6e0-497f-992a-b956843d3de7)
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/2a83bf60-ed2c-4df8-b743-16743f2496c5)

</details>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se que esté componente **não compoem** a parte superior da progress bar amarela, nem todo o resto que fica a cima da seleção da imagem. 

**Está parte a baixo não faz parte do componente**
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/2db87dff-c986-4fc3-8aa6-c8c1dfa77d89)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by marceana** [comment]
eu quero!!!

**Comment by JonasGz** [comment]
eu quero!!!
