### ISSUE TITLE
Criação do componente de vacinas

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/pet-dex-frontend#109]
**Describe the feature**
Criar o componente de vacinas.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 Essa task se trata de criar o componente de vacinas que atuará na tela de Petvet na etapa 8 do cadastro de pet.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Eu como usuário poderei adcionar as vacinas que o meu pet tomou.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Este componente é composto por um pequeno card inicial com um botão "Adcionar vacina" o qual é responsável por abrir um drawer onde o usuário poderá selecionar o tipo de vacina, a data em que foi realizada e o veterinário que aplicou.
Após confirmado os dados o drawer fecha e o componente agora apresenta uma tabela com a lista das vacinas cadastradas.

**Atente-se na implementação do componente na versão desktop e também na versão mobile.**

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Versão com nenhuma vacina adcionada:
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/dfdc959b-130e-4ec9-8db1-fc0c3391825b)

Drawer de seleção dos dados:
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/a4e9c378-9566-4de0-b7eb-722e84ce250a)

Versão com vacina adcionada:
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/1f0129d8-e949-4636-80d2-53d92f93317c)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
