### ISSUE TITLE
Criação da tela de Petvet

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/pet-dex-frontend#110]
**Describe the feature**
Criar a tela de Petvet.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Esta task é responsável pela criação da tela de Petvet, que é equivalente a etapa 8 do cadastro de pet.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Eu como usuário poderei informar alguns cuidados médicos do meu pet como se ele já é castrado, se necessita de cuidados especiais e quais são estes cuidados, e por fim as vacinas que o meu pet tomou.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

**Atente-se que os componentes da tela devem retornar o dado atualizado através de um evento de emitter para o componente pai.**

O desenvolvedor deverá utilizar os componentes abaixo para criar esta tela e suas funcionalidades:
- [x] #109 
- [ ] #65 

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Tela versão mobile:
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/1a60d415-c775-4125-bb16-f680aec34b61)

Tela versão desktop:
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/f36c6076-07ba-4f43-aaf7-c650a6cbfb5e)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se que esté componente não compoem a parte superior da progress bar amarela, nem todo o resto que fica a cima da seleção da imagem.

**Está parte a baixo não faz parte do componente:**
![image](https://github.com/devhatt/pet-dex-frontend/assets/90076846/1df78471-a560-4076-a6f9-18edeb8bfb3d)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
