### ISSUE TITLE
Componente de Drawer

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#118]
**Describe the feature**
Criar componente do Drawer.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 O componente do Drawer será uma funcionalidade que permitirá a renderização de conteúdo adicional de forma intuitiva e não intrusiva em diversas telas do site. Ele será posicionado no canto direito da tela e será ativado ao ser acionado por um botão. Assim como um modal, ele irá sobrepor o conteúdo principal da tela, mas de forma lateral, oferecendo uma maneira conveniente de exibir informações adicionais ou interações sem comprometer a visibilidade do conteúdo principal.
</details>

<details> 
  <summary>
    <b>Use case </b>
  </summary>
O Drawer será empregado em diversas situações no site, como por exemplo, quando for necessário solicitar dados adicionais do usuário ou oferecer opções complementares sem modificar o conteúdo principal da tela. Por exemplo, ao clicar no botão de adicionar vacina na página de cadastro do pet, o Drawer será acionado para exibir campos que precisam ser preenchidos da vacina do pet.
</details>
<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Atentar-se a:
- Título, que será setado por prop
- Botão de fechar no topo da página
- Botão de confirmar no canto inferior do componente, que emitirá ao ser clicado
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Desktop visual:

![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/9ba204ca-5b99-4944-95a5-9b86da064938)
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/a7655b93-fd90-4f66-b849-be6df24a0a24)

Mobile visual:

![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/bb374721-ee02-4e38-8ec1-2bb0ed3a1387)

Link do figma: https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&node-id=107-5&mode=design&t=A3aR7erq6Yau3YNW-0

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by RafaelLimaC** [comment]
Eu quero!!!
