### ISSUE TITLE
Router Service

### ISSUE THREAD

**Issue by Clerijr** [devhatt/pet-dex-frontend#119]
**Describe the feature**
Implementar serviço de roteamento cujo altera o componente de renderização de página e lida com a fila de rotas. 

<br>
<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O serviço deve:
- Dar `push state` e alterar a rota
- Dar `pop state` e alterar a rota
- Emitir evento de troca de rota

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

- O serviço deve receber um objeto de configuração com key: value pairs onde a key é uma rota e o value é um componente
- O serviço deve renderizar o componente da rota
- O evento de troca de rota deve emitir a rota atual e a rota anterior
- As rotas devem suportar slug parameter e query string

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
- É essencial que quem fazer a task fale com o @Alecell e o @diogocaronte 
- [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)
- [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event)
- [Custom Event](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)
- https://github.com/jscodelover/vanilla-routing

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by marceana** [comment]
Eu quero!!!

**Comment by JonasGz** [comment]
Eu quero!!!
