### ISSUE TITLE
Serviço de raças

### ISSUE THREAD

**Issue by muritadb** [devhatt/pet-dex-frontend#120]
**Describe the feature**
Serviço para lidar com recursos da raça dos pets

<details> 
  <summary>
    <b>Use Case</b>
  </summary>

- Listar raça
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
  
  - Usar a biblioteca axios para fazer as requisições.
  - Configurar o main route (para colocar apenas o path e evitar o domain)
  - Necessario informar as operações que está sendo executadas no usecase (console.log dos dados, ignorar a regra do eslint no arquivo)
  - Usar funções para a criação do serviço (não usar classes)
  - O endpoint utilizado será o... (perguntar para o @k1nha )

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
  - [Axios](https://axios-http.com/ptbr/docs/intro)
  - [Promises](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Promise)
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
[PETF-11 Bom dia](https://linear.app/devhatt/issue/PETF-11/bom-dia)

**Comment by DominMFD** [comment]
teste

**Comment by DominMFD** [comment]
oi

**Comment by DominMFD** [comment]
oi 3

**Comment by Sherlockzen** [comment]
opa

**Comment by Sherlockzen** [comment]
https://linear.app/devhatt/issue/PETF-42/servico-de-racas

**Comment by Sherlockzen** [comment]
alouuu

**Comment by juliaam** [comment]
Eu quero!!!
