### ISSUE TITLE
[PETF-52] [PETF-53] [PETF-54] [PETF-55] [PETF-56] [PETF-57] [PETF-58] [PETF-59] [PETF-60] [PETF-61] [PETF-62] [PETF-63] Criação de tela de data de aniversario de animal

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/pet-dex-frontend#137]
**Describe the feature**
Criar a tela de adicionar datas especiais para o animal

```
**Description**
```

* Criar a tela de adicionar datas especiais do animal
* Criar os componentes para ser dependente apenas dessa tela e não da aplicação

  **Implementation Details**

**ESSE COMPONENTE NECESSITA RETORNAR UM EVENTO TODA VEZ QUE TEM ALGUMA INTERAÇÃO USANDO EMIT**

Alguns componentes devem ser utilizados:

- [ ] #27
- [ ] #24

  **Visual Concepts**

![image](https://uploads.linear.app/86437c97-452d-47b9-a544-946a20c7bb21/64fe04d4-5500-42f5-ad29-55fa6b262f8b/d6314e40-41e6-4d2d-a0e0-5f263ca62a14?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2NDM3Yzk3LTQ1MmQtNDdiOS1hNTQ0LTk0NmEyMGM3YmIyMS82NGZlMDRkNC01NTAwLTQyZjUtYWQyOS01NWZhNmIyNjJmOGIvZDYzMTRlNDAtNDFlNi00ZDJkLWEwZTAtNWYyNjNjYTYyYTE0IiwiaWF0IjoxNzEyNzc5OTA5LCJleHAiOjMzMjgzMzM5OTA5fQ.Ag0KtIMPUmzwnkUf0LOjJQSLck8qZRL1Lg72wYfxTQQ)

![image](https://uploads.linear.app/86437c97-452d-47b9-a544-946a20c7bb21/f26e54ed-7720-47d4-9264-3544af2f5726/141bea0d-0842-4b9c-9e8f-021d915d0c4d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2NDM3Yzk3LTQ1MmQtNDdiOS1hNTQ0LTk0NmEyMGM3YmIyMS9mMjZlNTRlZC03NzIwLTQ3ZDQtOTI2NC0zNTQ0YWYyZjU3MjYvMTQxYmVhMGQtMDg0Mi00YjljLTllOGYtMDIxZDkxNWQwYzRkIiwiaWF0IjoxNzEyNzc5OTA5LCJleHAiOjMzMjgzMzM5OTA5fQ.fvdG3PtDJ6TMP7UbRCJMn8eKH5UiPTH-r_g_A5Xb2FU)

![image](https://uploads.linear.app/86437c97-452d-47b9-a544-946a20c7bb21/d9b92c0d-bd3b-43e3-baf3-93d018074559/880be9a5-c5c2-445a-bcd1-b8624f07dfb2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2NDM3Yzk3LTQ1MmQtNDdiOS1hNTQ0LTk0NmEyMGM3YmIyMS9kOWI5MmMwZC1iZDNiLTQzZTMtYmFmMy05M2QwMTgwNzQ1NTkvODgwYmU5YTUtYzVjMi00NDVhLWJjZDEtYjg2MjRmMDdkZmIyIiwiaWF0IjoxNzEyNzc5OTA5LCJleHAiOjMzMjgzMzM5OTA5fQ.xUyHrYlMeZAuREsFJUSIYo5Jc9OqZNMoQ6Z7lbzZVP4)

![image](https://uploads.linear.app/86437c97-452d-47b9-a544-946a20c7bb21/856a7687-7c99-411d-b2fd-90c7da660dbb/9858529a-9ca9-4b31-b70d-063de529a6f1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2NDM3Yzk3LTQ1MmQtNDdiOS1hNTQ0LTk0NmEyMGM3YmIyMS84NTZhNzY4Ny03Yzk5LTQxMWQtYjJmZC05MGM3ZGE2NjBkYmIvOTg1ODUyOWEtOWNhOS00YjMxLWI3MGQtMDYzZGU1MjlhNmYxIiwiaWF0IjoxNzEyNzc5OTA5LCJleHAiOjMzMjgzMzM5OTA5fQ.via_erjuJ2USr3nlcATGJtYiXt0qyP8geiY0oP9rFno)

```
**Additional Information**
```

\[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.\]

[PETF-63](https://linear.app/devhatt/issue/PETF-63/criacao-de-tela-de-data-de-aniversario-de-animal)

From [SyncLinear.com](https://synclinear.com) | [PETF-62](https://linear.app/devhatt/issue/PETF-62/%5Bpetf-63%5D-criacao-de-tela-de-data-de-aniversario-de-animal)

From [SyncLinear.com](https://synclinear.com) | [PETF-61](https://linear.app/devhatt/issue/PETF-61/%5Bpetf-62%5D-%5Bpetf-63%5D-criacao-de-tela-de-data-de-aniversario-de-animal)

From [SyncLinear.com](https://synclinear.com) | [PETF-60](https://linear.app/devhatt/issue/PETF-60/%5Bpetf-61%5D-%5Bpetf-62%5D-%5Bpetf-63%5D-criacao-de-tela-de-data-de-aniversario)

From [SyncLinear.com](https://synclinear.com) | [PETF-59](https://linear.app/devhatt/issue/PETF-59/%5Bpetf-60%5D-%5Bpetf-61%5D-%5Bpetf-62%5D-%5Bpetf-63%5D-criacao-de-tela-de-data-de)

From [SyncLinear.com](https://synclinear.com) | [PETF-58](https://linear.app/devhatt/issue/PETF-58/%5Bpetf-59%5D-%5Bpetf-60%5D-%5Bpetf-61%5D-%5Bpetf-62%5D-%5Bpetf-63%5D-criacao-de-tela-de)

From [SyncLinear.com](https://synclinear.com) | [PETF-57](https://linear.app/devhatt/issue/PETF-57/%5Bpetf-58%5D-%5Bpetf-59%5D-%5Bpetf-60%5D-%5Bpetf-61%5D-%5Bpetf-62%5D-%5Bpetf-63%5D-criacao-de)

From [SyncLinear.com](https://synclinear.com) | [PETF-56](https://linear.app/devhatt/issue/PETF-56/%5Bpetf-57%5D-%5Bpetf-58%5D-%5Bpetf-59%5D-%5Bpetf-60%5D-%5Bpetf-61%5D-%5Bpetf-62%5D-%5Bpetf-63%5D)

From [SyncLinear.com](https://synclinear.com) | [PETF-55](https://linear.app/devhatt/issue/PETF-55/%5Bpetf-56%5D-%5Bpetf-57%5D-%5Bpetf-58%5D-%5Bpetf-59%5D-%5Bpetf-60%5D-%5Bpetf-61%5D-%5Bpetf-62%5D)

From [SyncLinear.com](https://synclinear.com) | [PETF-54](https://linear.app/devhatt/issue/PETF-54/%5Bpetf-55%5D-%5Bpetf-56%5D-%5Bpetf-57%5D-%5Bpetf-58%5D-%5Bpetf-59%5D-%5Bpetf-60%5D-%5Bpetf-61%5D)

From [SyncLinear.com](https://synclinear.com) | [PETF-53](https://linear.app/devhatt/issue/PETF-53/%5Bpetf-54%5D-%5Bpetf-55%5D-%5Bpetf-56%5D-%5Bpetf-57%5D-%5Bpetf-58%5D-%5Bpetf-59%5D-%5Bpetf-60%5D)

<sub>From [SyncLinear.com](https://synclinear.com) | [PETF-52](https://linear.app/devhatt/issue/PETF-52/[petf-53]-[petf-54]-[petf-55]-[petf-56]-[petf-57]-[petf-58]-[petf-59])</sub>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)
