### ISSUE TITLE
[PETF-82] [PETF-83] [PETF-84] [PETF-85] [PETF-86] ta em conflito?

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/pet-dex-frontend#167]
asdfas

From [SyncLinear.com](https://synclinear.com) | [PETF-86](https://linear.app/devhatt/issue/PETF-86/ta-em-conflito)

From [SyncLinear.com](https://synclinear.com) | [PETF-85](https://linear.app/devhatt/issue/PETF-85/%5Bpetf-86%5D-ta-em-conflito)

From [SyncLinear.com](https://synclinear.com) | [PETF-84](https://linear.app/devhatt/issue/PETF-84/%5Bpetf-85%5D-%5Bpetf-86%5D-ta-em-conflito)

From [SyncLinear.com](https://synclinear.com) | [PETF-83](https://linear.app/devhatt/issue/PETF-83/%5Bpetf-84%5D-%5Bpetf-85%5D-%5Bpetf-86%5D-ta-em-conflito)

<sub>From [SyncLinear.com](https://synclinear.com) | [PETF-82](https://linear.app/devhatt/issue/PETF-82/[petf-83]-[petf-84]-[petf-85]-[petf-86]-ta-em-conflito)</sub>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)
