### ISSUE TITLE
Menu e itens

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#17]
**Describe the feature**
Implementação de um menu lateral responsivo com funcionalidade de drawer para a aplicação PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um menu lateral ("sidebar") que opere como um componente único e seja responsivo, adaptando-se tanto para a visualização desktop quanto mobile. Na versão mobile, o menu deverá ter um efeito de drawer (menu que se desliza), podendo ser aberto e fechado tanto através de um botão quanto por gestos de swipe.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O uso deste menu lateral aprimora a navegação do usuário, facilitando o acesso às diferentes seções da aplicação de maneira intuitiva e confortável em dispositivos móveis e desktops.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O menu deve ser implementado utilizando tecnologias web padrão, como HTML, SASS e JavaScript, garantindo a compatibilidade entre diferentes navegadores e dispositivos. Deve-se atentar para a usabilidade e acessibilidade, assegurando que o menu seja facilmente navegável por teclado e leitores de tela.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Referência visual do componente pode ser encontrada no layout do Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/776b2758-5b66-4de3-b2fb-4ced267af7f4)

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/5ec36314-eb4d-410f-87e0-f9f1a36a254a)

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/f0c82b1e-24e0-418f-8947-286cf3926905)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
O desenvolvimento deste componente deve seguir as diretrizes de código existentes, respeitando os padrões de projeto e garantindo a manutenção do código DRY. A implementação deve ser testada em diferentes dispositivos para garantir a responsividade e funcionamento adequado do efeito drawer.
</details>

**Perguntas a pendentes:**
- **Acessibilidade**: Como o menu lidará com a navegação por teclado e leitores de tela?
- **Estado Ativo**: Como o menu indicará qual página está ativa no momento?
- **Integração com o Estado Global**: Existe um estado global ou contexto que afetará o menu?

**Comment by JonasGz** [comment]
eu quero!!!
