### ISSUE TITLE
[PETF-86] [PETF-87] [PETF-88] [PETF-90] [PETF-92] ta em conflito?

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/pet-dex-frontend#171]
asdfas

[PETF-90](https://linear.app/devhatt/issue/PETF-90/ta-em-conflito)

From [SyncLinear.com](https://synclinear.com) | [PETF-88](https://linear.app/devhatt/issue/PETF-88/%5Bpetf-90%5D-ta-em-conflito)

From [SyncLinear.com](https://synclinear.com) | [PETF-87](https://linear.app/devhatt/issue/PETF-87/%5Bpetf-88%5D-ta-em-conflito)

<sub>From [SyncLinear.com](https://synclinear.com) | [PETF-86](https://linear.app/devhatt/issue/PETF-86/[petf-87]-[petf-88]-[petf-90]-[petf-92]-ta-em-conflito)</sub>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)
