### ISSUE TITLE
Criação do Componente de Avatar de Pet com Ação de Adição

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#18]
**Describe the feature**
Desenvolvimento de um componente interativo de avatar para adicionar pets no PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Criação de um componente de avatar no formato de um botão, que ao ser clicado redirecionará o usuário para a página de adicionar um novo pet. Este componente também deve apresentar uma mini animação de hover que muda a cor do ícone central.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Este componente facilitará o processo de adição de novos pets pelos usuários, melhorando a interatividade e a experiência geral do usuário na plataforma PetDex.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O componente deve ser implementado utilizando HTML, SASS e JavaScript. Deve-se prestar atenção especial à acessibilidade, garantindo que o componente seja facilmente navegável e acessível. A animação de hover deve ser sutil e não comprometer a usabilidade.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

O design do componente pode ser encontrado no layout do Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
A URL de redirecionamento para a página de adição de pet ainda não está disponível e deverá ser solicitada. A implementação da animação de hover e as mudanças de cor também devem ser detalhadas pelo designer.
</details>

**Perguntas Pendentes:**
- Qual é a URL exata para a página de adição de pet?
- Quais são os detalhes exatos da animação de hover, incluindo a mudança de cor do ícone?

**Recomendações:**
- Certifique-se de seguir as convenções e guias de estilo do projeto PetDex.
- Teste a acessibilidade do componente com leitores de tela e navegação por teclado.
- Mantenha o código DRY e reutilizável, evitando duplicações e favorecendo componentes modulares.

**Comment by carlosbryanp** [comment]
eu quero

**Comment by carlosbryanp** [comment]
eu quero!!!

**Comment by JonasGz** [comment]
eu quero!!!
