### ISSUE TITLE
[PETF-98] e agora

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/pet-dex-frontend#183]
vamo ve

<sub>From [SyncLinear.com](https://synclinear.com) | [PETF-98](https://linear.app/devhatt/issue/PETF-98/e-agora)</sub>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Sherlockzen** [comment]
lets bora

**Comment by DominMFD** [comment]
oi

**Comment by DominMFD** [comment]
oi

**Comment by DominMFD** [comment]
io

**Comment by Sherlockzen** [comment]
pq

**Comment by DominMFD** [comment]
oi

**Comment by Sherlockzen** [comment]
alou

**Comment by DominMFD** [comment]
oi

**Comment by Sherlockzen** [comment]
a partir

**Comment by diogocaronte** [comment]
https://github.com/devhatt/pet-dex-frontend/issues/183
