### ISSUE TITLE
Bom dia 2

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#184]
oioioioio

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
oi

**Comment by DominMFD** [comment]
oi2
