### ISSUE TITLE
Serviço de raças (copy)

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/pet-dex-frontend#185]
**Describe the feature**
Serviço para lidar com recursos da raça dos pets

```
**Use Case**
```

* Listar raça

  **Implementation Details**
  * Usar a biblioteca axios para fazer as requisições.
  * Configurar o main route (para colocar apenas o path e evitar o domain)
  * Necessario informar as operações que está sendo executadas no usecase (console.log dos dados, ignorar a regra do eslint no arquivo)
  * Usar funções para a criação do serviço (não usar classes)
  * O endpoint utilizado será o... (perguntar para o @k1nha )

    **Additional Information**
  * [Axios](https://axios-http.com/ptbr/docs/intro)
  * [Promises](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
oi

**Comment by Sherlockzen** [comment]
afff
