### ISSUE TITLE
Ajustes no Radio e Checkbox

### ISSUE THREAD

**Issue by marceana** [devhatt/pet-dex-frontend#188]
**Describe the bug**
Ajustar altura, largura, tamanho da circunferência do radio do componente Radio e Checkbox. Ajustar também a bolinha de dentro (radio) e borda para ficar mais próximo ao protótipo do figma.

<details open> 
  <summary>
    <b>Description</b>
  </summary>

  ![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/4b6b7548-3403-4674-9e95-739fb947454d)

![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/8ecc9cd9-3259-4fe5-a3ec-b7e964fadaa6)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by klebsonmateus** [comment]
eu quero!!!
