### ISSUE TITLE
Ajustes no componente Input

### ISSUE THREAD

**Issue by marceana** [devhatt/pet-dex-frontend#189]
**Describe the bug**
Ajustar algumas inconsistências no componente Input.

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   Ajustar border-radius do padding do prefix do componente para se ajustar ao protótipo.
</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>

Atual:
![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/ccb60bf7-7055-4edc-a2bf-b63b23d36712)

Protótipo:
![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/8016b59c-5f67-48bc-ab4b-c065dc94a172)

![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/7b1475d2-a7ae-4305-906b-064cd89f4b00)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by nicolasfreitas-dev** [comment]
Eu quero!!!
