### ISSUE TITLE
Implementação da Página Inicial Responsiva com Abordagem Mobile-First

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#19]
**Describe the feature**
Desenvolvimento da página inicial do PetDex com abordagem mobile-first, adequando-se também a visualizações desktop.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar a página inicial do PetDex, com foco na responsividade e design adaptável para dispositivos móveis e desktop. A página deve informar os usuários que ainda não cadastraram pets e proporcionar um caminho claro para o cadastro.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Esta página é crucial para engajar novos usuários e direcioná-los para adicionar seus pets à plataforma, sendo um ponto de partida para a interação com o site.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

A página deve seguir as diretrizes do layout fornecido, com atenção especial para a acessibilidade e experiência do usuário. O botão "Cadastrar pet" pode ser inicialmente um placeholder, com a necessidade de substituição futura por um componente estilizado.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

O design visual do componente pode ser visualizado no Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/3cf0ae13-57a0-4f46-98c9-99a15d755e29)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
A implementação deve ser feita utilizando as tecnologias padrão do projeto (JavaScript, SASS e HTML). Todos os componentes devem ser testados em diferentes dispositivos para garantir a responsividade e o funcionamento correto.
</details>

**Perguntas Pendentes:**
- Já existe um componente de botão estilizado para ser utilizado?
- Qual ação exata o botão "Cadastrar pet" deve realizar? Existe uma rota definida para o cadastro?

**Recomendações:**
- Assegure-se de seguir as práticas recomendadas para uma abordagem mobile-first.
- Priorize a performance e a acessibilidade em todas as implementações.
- Considere o uso de placeholders para elementos que ainda não foram finalizados, com lembretes claros para substituição futura.

**Comment by diogocaronte** [comment]
Eu quero!!!

**Comment by Alecell** [comment]
Ponto: 13
