### ISSUE TITLE
Criação de CI

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/pet-dex-frontend#197]
<details open>
  <summary>
    <b>Description</b>
  </summary>
Criar CI de testes, code-style e de build do projeto
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)
