### ISSUE TITLE
Criação e Estilização do Componente PetCard com Estados de Seleção

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#20]
**Describe the feature**
Implementação do componente PetCard para exibir informações de pets com interatividade de seleção.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um componente de cartão (PetCard) que apresente a imagem e o nome do pet. Este componente deve ter dois estados visuais: selecionado e desselecionado. No estado selecionado, o cartão deve ser destacado com uma borda azul.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O PetCard será utilizado para melhorar a experiência do usuário ao selecionar pets, fornecendo um feedback visual claro de qual pet está selecionado no momento.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O componente deve ser criado usando HTML, SASS e JavaScript, seguindo as diretrizes de design fornecidas no Figma. Deve ser responsivo e acessível, permitindo a navegação tanto por cliques quanto por teclado.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

As referências visuais para o componente estão disponíveis no layout do Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/59b98ec5-4774-4f9b-8014-b697476a7727)

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/9355c27e-9abd-4fef-8118-c61cdc452f51)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
É importante notificar o designer que a página de layout no Figma está com problemas de scroll, necessitando ajustes para visualização completa do design.
</details>

**Perguntas Pendentes:**
- Qual é o comportamento exato esperado ao interagir com o PetCard? Há alguma ação adicional além da alteração visual?
- Qual a ação de seleção deve ser vinculada ao estado do PetCard dentro do fluxo geral da aplicação?

**Recomendações:**
- Certifique-se de que o estado selecionado não interfira na legibilidade ou acessibilidade do cartão.

**Comment by GabrielBruno7** [comment]
eu quero !!!

**Comment by GabrielBruno7** [comment]
Eu quero !

**Comment by RafaelLimaC** [comment]
Eu quero!!!

**Comment by Alecell** [comment]
Ponto: 21
