### ISSUE TITLE
Repaginação do aquivo fonts.scss

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#208]
**Describe the feature**
O arquivo `fonts.scss` está ligeiramente além doque queríamos que ele fosse inicialmente, é preciso ajusta-lo de acordo com nossa real necessidade, pareada com o design.

<details open>
  <summary>
    <b>Description</b>
  </summary>

  Simplifique o arquivo de uma forma que ele possua apenas variáveis que definam os pesos de fonte, os estilos e os tipos, sem definições vinculadas a outros comportamentos como por exemplo `$buttonFontSize` ou coisas parecidas
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Essa task consiste basicamente em remover tudo que existe a baixo da linha 22 do arquivo `fonts.scss` e adicionar as outras variações de fonte no projeto, hoje o projeto possui 4 fontes e isso precisa ser ajustado.

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Consulte o arquivo `index.html` na importação do google fonts para verificar as fontes usadas.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by gomessgbr** [comment]
eu quero!!!
