### ISSUE TITLE
Implementação de Componente Input de Texto com Variantes Estilísticas

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#21]
**Describe the feature**
Desenvolvimento de um componente de campo de entrada de texto com variantes de estilo para o projeto PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Criar um componente de input de texto genérico que suporte as variantes 'standard' e 'outlined', bem como estados de erro e selecionado, conforme os padrões de design do PetDex.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O componente será usado em vários formulários da plataforma, permitindo uma experiência de usuário consistente e acessível em todo o projeto.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O input de texto deve ser implementado em HTML, com estilos em SASS e comportamento interativo via JavaScript. O desenvolvedor deve atender aos requisitos de acessibilidade, como etiquetas apropriadas e feedback visual para os estados de erro e foco.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

A especificação visual para o componente pode ser encontrada no Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/f3bd6e0b-1d57-4d82-a395-1a1f682455b3)

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/082a92cc-2428-4cc8-a596-aee18ee5e79a)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
As variações de estilo e os estados do componente devem ser claros e distintos para os usuários, seguindo as diretrizes de UI/UX fornecidas.
</details>

**Perguntas Pendentes:**
- Como o estado de erro deve ser visualmente representado além da borda?
- Há algum requisito específico para o comportamento do estado 'selecionado' do input?

**Recomendações:**
- Verificar com o time de design para esclarecer as variantes com erro e selecionado.
- Assegure-se de que a implementação seja modular e reutilizável, seguindo as diretrizes DRY.
- Testar extensivamente as funcionalidades do componente em diferentes navegadores e dispositivos.

**Comment by MateusHenriquegringo** [comment]
eu quero!!!

**Comment by Alecell** [comment]
Ponto: 13
