### ISSUE TITLE
Criação de Componente de Barra de Progresso

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#22]
**Describe the feature**
Desenvolvimento de uma barra de progresso controlada e personalizável para o projeto PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar uma barra de progresso controlada que aceite propriedades `min`, `max`, e `value`. Deverá permitir a personalização de estilos como cor, altura e largura por meio de SCSS, oferecendo flexibilidade para diferentes usos no projeto.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
A barra de progresso será usada para indicar o carregamento ou a conclusão de tarefas, melhorando a experiência do usuário ao fornecer feedback visual imediato.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O componente deve ser desenvolvido utilizando HTML, SASS e JavaScript, assegurando que seja possível sobrescrever estilos por meio de classes SCSS. A transição do progresso deve ser suave e bem animada para melhorar a usabilidade.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Confira o layout no Figma para visualizar o componente: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/5f7fa07f-1395-4319-b1a6-eff2b4b95b46)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
A implementação deve ser consistente com a identidade visual do PetDex e seguir as melhores práticas de acessibilidade web.
</details>

**Perguntas Pendentes:**
- A barra de progresso deve interagir com outros componentes ou triggers na aplicação?

**Recomendações:**
- Realize testes cruzados para garantir que a personalização funcione corretamente em diferentes navegadores.
- Verifique o uso correto das propriedades de acessibilidade, como `aria-valuenow`, `aria-valuemin` e `aria-valuemax`.

**Comment by MilaPassos** [comment]
Eu quero!!!

**Comment by Alecell** [comment]
Ponto: 21

**Comment by lemoscaio** [comment]
### Deixar uma dica já de um jeito de chegar numa barrinha legal:

A ideia é fazer uma div que vai representar o fundo e uma div dentra que vai representar o preenchimento da barra.
Utilizando o `position: absolute` você consegue manipular a posição em relação à div com `position: relative` acima.

```html
<div class="progress-bar-background" style="position: relative">
   <div class="progress-bar-foreground" style=`width:${progress}; position: absolute`></div>
</div>
```

PS: Peço perdão se as tags não estiverem com a sintaxe certinha.

### Referência de vídeo que mostra a aplicação desse conceito na prática já no tempo exato:

https://youtu.be/yP5DKzriqXA?si=B4JXf3j7E9RJPyDB&t=17682

**Comment by JonySamarelli** [comment]
Eu quero!!!
