### ISSUE TITLE
Testes da página de peso do pet

### ISSUE THREAD

**Issue by marceana** [devhatt/pet-dex-frontend#220]
**Describe the feature**
Criar testes da página de peso do pet

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Issue 97](https://github.com/devhatt/pet-dex-frontend/issues/97)
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by marceana** [comment]
Eu quero!!!
