### ISSUE TITLE
Teste para a pagina PetRegisterPage

### ISSUE THREAD

**Issue by muritadb** [devhatt/pet-dex-frontend#225]
**Describe the feature**
Criar testes para a pagina de cadastro de raça de Pet

**Additional Information**
 
  
[ Issue 93 da task ](https://github.com/devhatt/pet-dex-frontend/issues/93)
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
