### ISSUE TITLE
Ajustes nos componentes de radio e checkbox

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#227]
**Describe the bug**
1. Componentes de botões de radio e checkbox com erros
2. Componente de radio sem variações de estilo

<details open> 
  <summary>
    <b>Description</b>
  </summary>
1. Os componentes de radio e checkbox possuem erros na chamada de funções e na declaração dos eventos, necessário que seja alterado para o bom funcionamento dos componentes. 
2. Necessário que no componente de radio tenha uma prop para uma variação no componente de rádio. Essa variação é para remover a borda do radio. 
</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>
 
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/dd761700-cc18-4ae4-8896-fb607f8a75d9)

![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/65ec0afb-3c9a-4388-9c6c-431f449e7377)
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/488d415a-b7af-4309-b096-827202dc3e5f)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
É necessário fazer a checagem e melhorias nos dois componentes(checkbox e radio), pois os dois apresentam inconsistências.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by klebsonmateus** [comment]
eu quero!!!
