### ISSUE TITLE
Criar o componente Add Pet Page

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#229]
**Describe the feature**
Criar o componente que será responsável pela adição do Pet. Esse componente deve ser o pai de todos os componentes que compõem as etapas de adição de pet.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  A página de adição de pet importa todas as etapas de adição de pet, adicionando o progress, o visual clue da etapa e o titulo da página.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Quando o usuário clicar em `adicionar pet` essa página irá abrir e haverá um sliding entre cada etapa de adição de pet até a conclusão do formulário.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

  Usar o componente de sliding que **já existe** no projeto
  Usar o componente de Progress **já existente** no projeto

  Lembre-se de atualizar o estado do progress bar e da etapa atual (texto 1/9) de acordo com a troca do slide.
  
  Para essa página, deverá ser utilizado o margin negativo para sobrepor o padding da home, para que o componente de 
  progress, e o footer, de concluir, fique sobreposto em toda a tela
  
  Não se esqueça de criar uma variável do valor do padding e de utilizá-la, para que seja utilizada também no margin 
  negativo e facilite a manutenção

  ![image](https://github.com/devhatt/pet-dex-frontend/assets/134434652/dc17cf00-2765-438a-ae42-2f171ed48b4c)

 ![image](https://github.com/devhatt/pet-dex-frontend/assets/134434652/7fa69754-9194-4cdd-91e0-2341c97d5687)

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
  
  Em vermelho é o conteúdo que o AddPetPage possuirá.
  Em azul é o conteúdo importado de uma etapa do AddPetPage, esse conteúdo será trocado de acordo com a etapa que o usuário está do `slider`

  ![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/f1cb9fa7-791d-4a82-aee2-18d970ca5024)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se de seguir o figma!

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)
