### ISSUE TITLE
Desenvolvimento de Componente Slider com Controle de Navegação

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#23]
**Describe the feature**
Criação de um componente de Sized Selector para seleção entre diferentes tamanhos de Pet.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um componente Sized Selector que permita ao usuário selecionar entre diferentes tamanhos de Pet. O componente deve ser capaz de selecionar entre os tamanhos para a navegação programática. Deve haver eventos que informem o card atual sempre que o card for selecionado.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O componente será utilizado no cadastro inicial do Pet para permitir uma navegação intuitiva, fazendo assim uma seleção sim e adequada do Pet
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O componente deve ser implementado com a funcionalidade de touch para dispositivos móveis e opções de controle programático.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Embora não haja uma representação visual do componente em ação, o layout atual pode ser visualizado no Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/8916cdcc-2bc1-48f8-90ed-d3086bf9b6a5)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Deve-se assegurar que o componente seja responsivo e acessível, seguindo as diretrizes de ARIA para componentes de select.
</details>

**Perguntas Pendentes:**
- Como os itens adjacentes devem ser editados? Existe alguma diretriz de estilo ou funcionalidade específica para isso?
- Existe algum requisito específico para a animação entre os slides, ou isso deve ser definido em colaboração com a equipe de design?

**Recomendações:**
- Considerar a implementação de testes automatizados para garantir a funcionalidade do slider em diferentes cenários de uso.
- Documentar como os eventos de `next()` e `prev()` podem ser acessados e utilizados por outros componentes ou páginas.
- Avaliar a utilização de bibliotecas existentes para a funcionalidade de select ou a necessidade de desenvolver uma solução personalizada.

**Comment by Alecell** [comment]
Ponto: 34

**Comment by buuninbee** [comment]
eu quero!!!

**Comment by Sherlockzen** [comment]
teste

**Comment by Sherlockzen** [comment]
syncado

**Comment by Sherlockzen** [comment]
https://linear.app/devhatt/issue/PETF-18/desenvolvimento-de-componente-slider-com-controle-de-navegacao

**Comment by Sherlockzen** [comment]
ae

**Comment by Sherlockzen** [comment]
batata frita

**Comment by DominMFD** [comment]
oi

**Comment by DominMFD** [comment]
oi

**Comment by JonasGz** [comment]
Eu quero!!!
