### ISSUE TITLE
Criar a rota para os botões de adicionar pet

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#230]
**Describe the feature**
Fazer o link dos botões de adicionar pet, para a página `AddPetPage`. 

<details open>
  <summary>
    <b>Description</b>
  </summary>
  
  Na página inicial do PetDex existe dois botões que levam para a página `AddPetPage`, esses botões são estes marcados em vermelho:
  
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/7fe06340-4fda-45ae-9a84-fd8bf135bc60)

É preciso que ao clicar neles o usuário seria redirecionado para a página `AddPetPage`.

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  O usuário precisa ter acesso a página de adição de pet através dos botões que referenciam essa adição.
  
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

  Usar o módulo de roteamento já existente para fazer o redirecionamento quando clicar no botão. Em caso de dúvidas de como usar o routing falar com @JonasGz 

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
  Existe uma possibilidade de que seja possivel usar o `<a>` para fazer o routing e mesmo assim ser um routing em formato SPA, lembre-se de falar com o @JonasGz

Lembre-se de seguir o figma! 
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by wendesongomes** [comment]
eu quero!!!
