### ISSUE TITLE
Componente Pet Avatar

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#231]
**Describe the feature**
Verificar se o Pet Avatar existe e se não existir criar. Esse componente representa visualmente no sidebar a existência de pets cadastrados.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  
  Precisamos criar o componente de `PetAvatar` cujo será colocado no menu lateral da página. O petavatar pode ser clicado e populado de acordo com a API de listagem de pets cadastrados. Esse serviço já deve existir quando iniciar esta tarefa.

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  O usuário precisa ter um modo fácil de visualizar os pets cadastrados mesmo quando não está na `home`.

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

  O `PetAvatar` deve ser clicável e, quando for, redirecionar para a página de `PetPerfil` do pet clicado. Esse redirecionamento deve ser feito com o router já existente na página. Em caso de dúvidas falar com @JonasGz 

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/64487ffb-9056-4768-8998-2f8ad1e177b0)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
  Lembre-se de seguir o figma!
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by nathalia-84** [comment]
Eu quero!!!
