### ISSUE TITLE
Criar o mock da Api

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#236]
**Describe the feature**
Como a API do backend ainda não está preparada para receber requests vamos usar um mock-api local para simular nossas requests e fazer nossos componentes se comunicarem com serviços.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  
  Precisamos que nosso projeto possua uma API mockada (sem ser web) para que possamos simular requests tanto de post quanto de get para que possamos lidar com os dados.

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

  Usar o package do NPM chamado [json-server](https://www.npmjs.com/package/json-server), esse package permite que tenhamos um arquivo json no root do projeto e esse json servirá como uma "api" para nosso projeto.

Sua missão tambem inclui colocar nesse json as API's que vamos precisar, elas são:
- User API
  - Dados do usuário
  - Configurações de conta
    - Linguagem preferida
    - Se deseja ou não receber atualizações por email
- Pet API
  - Cadastro
  - Listagem
  - Busca por ID
- Raça API
  - Listagem de raças

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se de seguir o figma!
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by nicolasfreitas-dev** [comment]
eu quero!!!
