### ISSUE TITLE
Criar o Serviço de Listar Pets

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#237]
**Describe the feature**
Criação do serviço de listagem de pets. Esse serviço deve fazer uso o `mock-api` já existente.

**Iniciar apenas quando:**

- [x] #236 

<details open>
  <summary>
    <b>Description</b>
  </summary>

  Precisamos criar um serviço de listagem de pets. Esse serviço é uma função que deve ser colocada no serviço de `PetService`, o `PetService` é um objeto cujo possui métodos dentro dele.

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Nós devs precisamos ter um meio de fazer requests de forma desacoplada, pra isso criamos serviços separados permitindo assim o reuso.
  
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

  Esse serviço deverá receber um id de um usuário, assim, baseado no id do usuário teremos a lista de pets que esse usuário possui. Essa request é uma promise e o serviço deve lidar com os possiveis erros de API retornando para o _caller_ apenas o dado ou um objeto de erro sem propagar o erro para a aplicação.

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se de seguir o figma!
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by ClaudioBioni** [comment]
Eu quero!!!
