### ISSUE TITLE
Criar Formulario de Login

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#239]
**Describe the feature**
Criação do formulário de login isoladamente como um componente único.

<details open>
  <summary>
    <b>Description</b>
  </summary>

  Criar o formulário de login onde será a primeira página quando o usuário não tiver conta. Esse é apenas o formulário que eventualmente será colocado na página.

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Eu como usuário quero um formulário onde posso logar na página e acessar a aplicação.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

  Esse componente deve ser feito usando os componentes já existentes no projeto. Ele também deve ser escalável em largura e altura. 

O componente deve ter uma função não implementada que será onde será chamado o serviço de login para o login acontecer.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/fd72777c-25b8-4e1c-907d-944c7b4b3c38)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se de seguir o figma!
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by muritadb** [comment]
Eu quero!!!

**Comment by Mathh19** [comment]
Eu quero!!!
