### ISSUE TITLE
Implementação de Campo de Upload de Imagem com Animação de Destaque

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#24]
**Describe the feature**
Desenvolvimento de um campo de upload de imagem com animação de pulsação para o PetDex, seguindo o design especificado.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar um input de imagem que permita aos usuários fazer upload de uma foto principal para o perfil de seu pet. Este componente deve incluir uma animação sutil de pulsação ao redor do círculo para chamar a atenção para a ação de upload.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Este campo de imagem será usado na criação ou edição do perfil de um pet, permitindo que os usuários personalizem o perfil adicionando uma foto.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O campo deve ser implementado com um feedback visual claro para o usuário, tanto para o estado de espera do upload quanto para quando uma imagem é selecionada. A animação de pulsação deve ser suave e não intrusiva.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

As representações visuais podem ser encontradas no layout do Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/18a476e0-f571-4f83-9bc7-d00157bc4d7d)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
O componente deve ser responsivo e acessível, com suporte a leitores de tela e interações via teclado.
</details>

**Perguntas Pendentes:**
- A animação de pulsação tem especificações de duração ou estilo que devem ser seguidas?
- Existe uma limitação no tamanho ou formato do arquivo de imagem que pode ser carregado?

**Recomendações:**
- Testar a acessibilidade da animação e do componente de upload com usuários reais e ferramentas automatizadas.

**Comment by nathaliaazvdo** [comment]
Eu quero!!!

**Comment by Alecell** [comment]
Ponto: 21
