### ISSUE TITLE
Criar o Serviço de Login

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#241]
**Describe the feature**
Criar o serviço de login do usuário.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Criação do serviço de login do usuário onde serão passados os dados necessários ao login.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Será utilizado ao se clicar em **Entrar** na tela de login do usuário, é responsável por verificar os dados recebidos e realizar o login ou não do usuário.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O serviço de login se trata de uma função onde terão como parâmetros (email e senha) os dados do usuário coletados pela página de **login**. Esse serviço deve ser criado na pasta de **services** do projeto.
Este service deve ser responsável por verificar os dados e então emitir uma resposta de sucesso ou erro quanto ao login do usuário em questão.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
É interessante escrever um código claro e de boa leitura para todos! E sempre que necessário pergunte e tire dúvidas em nosso [Discord](https://discorg.gg/devhatt)
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by gustavogularte** [comment]
Eu quero!!!
