### ISSUE TITLE
Criar o formulário de Criação de conta

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#242]
**Describe the feature**
Criar o formulário referente a criação da Petconta.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Este componente se trata de um formulário onde será realizado o cadastro do usuário a fim de que ele inicie a utilização do app.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O formulário será utilizado na página de **Cadastro de Pet Conta** ou cadastro de conta.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Ele é composto de vários outros componentes já existentes na aplicação conforme lista abaixo:
1. Button - Obs: Os botões **Google** e **Facebook** precisam ser criados já que só existem nesta página.
2. Input - Obs: O input não precisa ser exatamente conforme o figma, com o label meio que inserido na borda do componente, basta um label logo acima do input.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/134434652/e3613e12-c967-4ceb-980e-897bb0aed3e4)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Deve ser seguido o figma do projeto, link abaixo:
https://www.figma.com/design/ZQ5mPH1j2snuiVpkp68EI5/PetDex?node-id=107-5&t=uhyPuCsbueOLy9AU-0
Atente-se para algumas observações pontuadas nos *detalhes de implementação* desta task.
Lembre-se de garantir a emissão desses dados para que a página possa recebê-los e dar continuidade a funcionalidade.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by nicolasfreitas-dev** [comment]
eu quero!!!
