### ISSUE TITLE
Criar o componente de troca de Senha

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#245]
**Describe the feature**
Criar o componente para substituição/troca de senha.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Os usuários da aplicação devem conseguir alterar a sua senha.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Nas configurações de conta, o usuário terá o botão para *trocar a senha*, ao clicar nele será invocado o drawer que já foi criado e dentro dele será carregado o conteúdo correto referente à troca de senha.
Ao finalizar e clicar em salvar o componente deve emiter as informações para a página de conta para prosseguir com a funcionalidade de trocar senha.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Esta funcionalidade está acompanhada de vários componentes já existentes na aplicação, listo aqui os que serão utilizados:
1. Componente de Drawer
2. Input de texto
3. Button

Lembre-se que você precisa emitir os dados para a página ao finalizar o processo (ao clicar em salvar).

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/134434652/74a2bf1b-c0d7-41f2-a13b-57749f6eef45)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Sempre se atente ao nosso [Figma](https://www.figma.com/design/ZQ5mPH1j2snuiVpkp68EI5/PetDex?node-id=107-5&t=uhyPuCsbueOLy9AU-0)
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Clerijr** [comment]
eu quero!!!
