### ISSUE TITLE
Remover os comentários de Eslint e resolve-los

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#248]
**Describe the feature**
Deverá remover os todos os comentários de Eslint do arquivo `src/components/Drawer/index.spec.js` e resolver seus devidos errors.

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/134434652/7c75189e-20e9-4a6b-9eea-ecf5ab1fe799)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
