### ISSUE TITLE
Componente de text area

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#250]
**Describe the feature**
1. Deve desenvolver um componente de text area que será utilizado em diversas páginas da aplicação.
2. Deve colocar os componentes nos locais que ele deve ser utilizado (página de petvet issue #110)

<details open>
  <summary>
    <b>Description</b>
  </summary>
 O componente de text area é responsável por receber um texto de várias linhas, ele se expande conforme há mais texto digitado. Além disso, ele deverá ser implementado na página de petvet, conforme issue #110 
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Será utilizado principalmente em formulários da aplicação.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Atente-se ao fato de que ele deve possuir as seguintes props: 
- name ( nome para controle do componente)
- placeholder (texto de exemplo ou dica do que deve ser inserido)
- ~rows (quantidade de linhas visíveis)~
- ~cols ( quantidade de caracteres visíveis por linha~
- maxlength (número máximo de caracteres que podem ser inseridos)
- required (indica se o campo é obrigatório ou não)
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Desktop:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/51c6aa14-aa65-46dd-94fa-d1920f541061)

Mobile:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/2022729c-0425-4d1b-9431-d862d64e3c7e)

Text area utilizado no cadastro de pet
link do figma: https://www.figma.com/design/ZQ5mPH1j2snuiVpkp68EI5/PetDex?node-id=107-5&t=FkPnR8q1SqPZogWe-0

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Mathh19** [comment]
Eu quero!!!
