### ISSUE TITLE
Estruturar o projeto para ter pastas como uma SPA

### ISSUE THREAD

**Issue by muritadb** [devhatt/pet-dex-frontend#251]
**Describe the feature**
O projeto esta crescendo e precisamos estrutura-lo para que tenha uma melhor estrutura, pensando nisso e em melhores praticas temos que estruturar os diretorios como uma app SPA.

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[SPA](https://developer.mozilla.org/en-US/docs/Glossary/SPA)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by muritadb** [comment]
eu quero!!!
