### ISSUE TITLE
Implementação de Componente Input Range Dinâmico

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#26]
**Describe the feature**
Desenvolvimento de um componente de input range para ajuste de valores, como o peso no PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar um componente interativo de input range que permita ao usuário ajustar valores movendo a régua com o dedo ou o mouse. Este componente deve apresentar uma animação suave e permitir a configuração de valores mínimos e máximos, além de expor eventos para mudanças em tempo real e ao finalizar a interação.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
Este componente permitirá aos usuários do PetDex ajustar com precisão valores como o peso do pet, oferecendo uma interface intuitiva e amigável para uma experiência de usuário aprimorada.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
O componente deve ser responsivo e acessível, com suporte para interação tanto em dispositivos móveis quanto desktops. Deve-se considerar a possibilidade de sobrescrita de estilos via SCSS para facilitar a personalização conforme necessário.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
O conceito visual atual pode ser consultado no Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/5f19b113-00c8-4f0e-aca3-21d706b3817a)

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/c8e73922-64c5-401f-b83b-fb137b948c8e)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
Deve-se garantir que o componente siga as melhores práticas de usabilidade e acessibilidade, como diretrizes de ARIA para inputs do tipo range.
</details>

**Perguntas Pendentes**
- Quais são as especificações para a animação de mudança do range?
- Existem diretrizes de estilo específicas para o estado "erro" do componente?
- Como o valor do range será integrado com o estado global do aplicativo ou gerenciamento de estado local?

**Comment by Alecell** [comment]
Ponto: 34

**Comment by anthonymanoel** [comment]
Mim dê papai, eu quero.

**Comment by anthonymanoel** [comment]
eu quero!!!

**Comment by anthonymanoel** [comment]
Eu quero!!!

**Comment by anthonymanoel** [comment]
Coe, terminando só falta a weight box manual e consertar o responsivo.

**Comment by anthonymanoel** [comment]
![image](https://github.com/devhatt/pet-dex-frontend/assets/72582172/0f3b5096-673e-469c-aa23-3f276a737982)

é para fazer isso aqui?

**Comment by RafaelLimaC** [comment]
Eu quero!!!
