### ISSUE TITLE
Teste para a página de Petvet

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#260]
**Describe the feature**
Criação de testes para a página de petvet, issue #110 

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Devem ser feitos testes unitários para a página de petvet, da issue #110 
</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
