### ISSUE TITLE
Atualizar componente TextInput

### ISSUE THREAD

**Issue by Mathh19** [devhatt/pet-dex-frontend#263]
**Describe the feature**
Atualizar para que o input contenha um ícone clicável.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Atualmente o ícone do input é apenas visual.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Adicionar um ícone clicável ao componente aumenta sua utilidade no projeto. Isso permite que o componente seja utilizado, por exemplo, como um campo de texto para senha, onde o ícone pode alternar a visibilidade da senha para o usuário.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

É importante garantir que o ícone esteja corretamente posicionado dentro do campo de texto e que não interfira na entrada de texto, mantendo um espaçamento adequado.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/67031321/51345c29-751b-4e32-b066-f0b1b95d1bcb)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Ao implementar a mudança no componente de input, é necessário atualizar o uso dele no formulário de login para que o campo de senha tenha a funcionalidade de exibir e esconder a senha.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by jessicasantosb** [comment]
Eu quero!!!
