### ISSUE TITLE
Vincular componente Pet Avatar com API

### ISSUE THREAD

**Issue by nathalia-84** [devhatt/pet-dex-frontend#267]
**Describe the feature**
O componente Pet Avatar deve ser populado de acordo com a API de listagem de pets cadastrados. Esse serviço já deve existir quando iniciar esta tarefa.

**Iniciar apenas quando:**
 - #237

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

<img src="https://private-user-images.githubusercontent.com/13935760/331819688-64487ffb-9056-4768-8998-2f8ad1e177b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjY1MzksIm5iZiI6MTcxODU2NjIzOSwicGF0aCI6Ii8xMzkzNTc2MC8zMzE4MTk2ODgtNjQ0ODdmZmItOTA1Ni00NzY4LTg5OTgtMmY4YWQxZTE3N2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE5MzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1N2U1ZDAxZWM5N2JiNWNlMGVjYTliOTA0MTAwYTc1MzNkODAyOTA0MzE4MjZjZTdmYzkxNzM1YTEyMjM2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLkqYhYwXhMvNIgdvxsnAphFVkozwH0ILRt_2z9XmSw"/>

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
O componente Pet Avatar já foi implementado, no entanto, está sendo populado com dados mockados até o momento. 
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by EdiltonOliveira** [comment]
Eu quero!!!
