### ISSUE TITLE
Fazer funcionalidade de scroll quando houver mais de 5 pets

### ISSUE THREAD

**Issue by nathalia-84** [devhatt/pet-dex-frontend#268]
**Describe the feature**
Implementar a funcionalidade de scroll na seção "Seu pet", quando houver mais de 6 pets a serem listados.

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

<img src="https://github.com/devhatt/pet-dex-frontend/assets/64925426/51587eb6-e76c-4c69-bb53-31c76bac9edd"/>

</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by gustavogularte** [comment]
Eu quero!!!
