### ISSUE TITLE
Corrigir pipiline de eslint

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/pet-dex-frontend#270]
Foi reportado pela comunidade que o workflow de code-style não estava triggando corretamente nos arquivos, deixando erros de eslint passar. 
Foi discutido com o @Alecell que o workflow deve triggar todos os arquivos

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)
