### ISSUE TITLE
Inserção do text área na petvet page

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#272]
**Describe the feature**
Inserção do componente de text área no componente de página pet vet

<details open>
  <summary>
    <b>Description</b>
  </summary>
  O objetivo dessa tarefa é de inserir o text área no componente de página do petvet, pois quando a página foi criada, o text área não estava disponível para ser inserido normalmente. Sendo assim, é necessário que seja implementado corretamente, conforme outros campos do formulário da página.

Pendente da issue: #250 
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
Utilizado na página de petvet para que seja preenchido o campo de cuidados especiais.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

1. Só deve ser requirido caso o botão/radio 'Sim' seja selecionado
2. Deve ser emitido no formulário conforme outros campos da página de Petvet

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Desktop:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/0064e83e-d973-433e-a175-0382129ffcde)
Mobile:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/e45d6dc8-a3e0-4e76-b196-b2e448d21a0d)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Link do figma: https://www.figma.com/design/ZQ5mPH1j2snuiVpkp68EI5/PetDex?node-id=0-1&t=9wgmZV3NRRX5mqXs-0
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by gustavogularte** [comment]
eu quero!!!
