### ISSUE TITLE
Criar o serviço de registro de usuário

### ISSUE THREAD

**Issue by nicolasfreitas-dev** [devhatt/pet-dex-frontend#279]
**Describe the feature**
Criar serviço de registro de usuários.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 
Criação do serviço de registro para novos usuários utilizando o dados coletados pelo formulário do componente de registro.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Esse serviço irá ser iniciado quando um novo usuário clicar no botão "**Cadastrar**" que se encontra no formulário de registro. Ele faz a verificação dos dados fornecidos pelo usuário e realiza o cadastro caso os dados estejam corretos.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O serviço de registro de usuário deve ser uma função que irá receber como parâmetro os dados fornecidos pelo usuário no ato do preenchimento do formulário (nome, sobrenome, email, senha, etc). O serviço em questão deve ser responsável pela verificação dos dados coletados e então emitir uma resposta de sucesso ou fracasso durante o ato de registro do usuário. Por fim, atente-se ao local de criação deste serviço, ele deve ser criado na pasta "**services**" do projeto.

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Tente seguir boas práticas para um código organizado e facilitar a leitura de todos. Qualquer dúvida os membros da comunidade estão sempre disponíveis no discord para ajudar.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
eu quero!!!
