### ISSUE TITLE
Criação de Componente Tabber Dinâmico para Navegação entre Conteúdos 

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#28]
**Describe the feature**
Implementação de um componente tabber dinâmico que facilitará a navegação entre diferentes conteúdos e seções dentro do PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um componente tabber que aceite um array de objetos como parâmetro, onde cada objeto representa uma aba e seu conteúdo correspondente. O componente deverá alternar entre as abas e exibir o conteúdo relevante sem recarregar a página.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  O componente tabber será utilizado em várias áreas do PetDex para proporcionar uma experiência de usuário mais organizada e fluida, permitindo a fácil transição entre diferentes seções como informações sobre pets, guias de cuidados, e histórico médico.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
  O componente deve ser responsivo e acessível, com suporte a teclado e leitores de tela. As abas devem ser controláveis programaticamente e o estado ativo deve ser claramente visível. O design deve seguir as diretrizes fornecidas no layout do Figma.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
  O layout visual e as diretrizes de design podem ser encontrados no seguinte link do Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/5d09816a-96ad-4b29-aad5-6ea29dfc90f8)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  É importante que o desenvolvimento do componente siga as práticas recomendadas de usabilidade e acessibilidade, para garantir uma experiência consistente e inclusiva para todos os usuários.
</details>

**Perguntas Pendentes**
- Qual deve ser o comportamento exato quando alternar entre as abas? Há alguma transição visual específica?
- Existem requisitos específicos para a exibição do ícone e do nome na aba?
 
**Recomendações**
- Teste a acessibilidade do componente com ferramentas como o Lighthouse e assegure-se de seguir as diretrizes WCAG.

**Comment by anaahnb** [comment]
Eu quero!!!

**Comment by Alecell** [comment]
Ponto: 21

**Comment by Alecell** [comment]
Reassignei pq da mensagem no disc!

**Comment by RafaelLimaC** [comment]
Eu quero!!!
