### ISSUE TITLE
Centralizar as regras de validação de senha

### ISSUE THREAD

**Issue by DominMFD** [devhatt/pet-dex-frontend#287]
**Describe the feature**
Atualmente temos 3 componentes que utilizam uma própria validação de senha, essa tarefa consiste em centralizar essa validação e fazer com que os componentes utilizem a mesma validação.

Os componentes citados são: 
- `LoginForm`
- `ChangePassword`
- `RegisterForm`

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

 Os componentes devem utilizar a mesma função de validação de senha e não a sua respectiva validação, deve ser criado uma função de validação para nossa aplicação e utilizar ela em todos esses componentes.

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by EdiltonOliveira** [comment]
Eu quero!!!
