### ISSUE TITLE
Implementação de Recurso de Swiping

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#29]
**Describe the feature**
Integração de um recurso de swiping para melhorar a interação do usuário com elementos swipeable como abas e sliders no PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar um recurso de swiping que reconheça gestos de toque para realizar ações como fechar uma aba ou voltar ao slide anterior. Deve-se explorar a viabilidade de implementar com JavaScript nativo ou integrar uma biblioteca externa.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  O recurso de swiping será utilizado para melhorar a experiência do usuário em dispositivos móveis, permitindo ações intuitivas como navegar entre slides ou fechar abas com gestos de toque.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
  Avaliar a API de Touch e Pointer Events do JavaScript nativo para implementar o swiping. Se necessário, avaliar e integrar bibliotecas de terceiros que ofereçam uma solução robusta e testada para o swiping.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
  Não há representações visuais para esta funcionalidade, uma vez que está relacionada com a interação do usuário, mas o design e comportamento deverão ser consistentes com a experiência geral do PetDex.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  Deve-se garantir que o recurso de swiping não interfira com a navegação padrão do navegador e que seja acessível e responsivo.
</details>

**Perguntas Pendentes**
- O JavaScript nativo já oferece suporte adequado para os requisitos do swiping ou será necessário uma biblioteca externa?
- Existem preferências específicas quanto à escolha de bibliotecas de terceiros para swiping?

**Recomendações**
- Realizar uma pesquisa inicial para determinar se as APIs nativas de eventos de toque são suficientes para a tarefa.
- Se for necessário usar uma biblioteca de terceiros, escolher uma que seja leve, bem documentada e amplamente adotada pela comunidade.
- Incluir testes para garantir que o recurso de swiping funcione como esperado em diferentes dispositivos e navegadores.

**Comment by Alecell** [comment]
Ponto: 21

**Comment by JonySamarelli** [comment]
Eu quero
