### ISSUE TITLE
Retirar borda do componente de radio na petvetpage

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#294]
**Describe the feature**
É necessário que a borda do componente seja retirada para que o layout seja fiel ao do figma. 

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Quando a página do petvet foi criada, ainda não existia a variação para o componente de radio, sendo assim, hoje em dia, essa parte do layout não está compatível com a do figma. Então, é necessário que seja usada a variação do radio sem a borda e de ajuste do seu css.
</details>

<br>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Não é necessário mexer no estilo do componente de radio, a variação já existe, é necessário apenas usá-la.
Quando o radio ficar sem a borda, utilizando a variação, é preciso que o css seja ajustado caso necessário (caso falte alguma margin ou padding entre os dois radios)

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Componente atual:
![image](https://github.com/user-attachments/assets/0eb60ae5-5e9c-4bce-8a66-796478de5150)

![image](https://github.com/user-attachments/assets/022cb82f-b00f-4423-8d21-4c8618275a5a)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Seria bom verificar se o estilo final dessa tela seria com o radio arredondado ou quadrado, conforme o do figma.

![image](https://github.com/user-attachments/assets/437cd92e-b58b-45d0-b882-4ba1921d4996)

![image](https://github.com/user-attachments/assets/470749a6-bf04-4a2c-8935-472c5910d96f)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Mathh19** [comment]
Eu quero!!!
