### ISSUE TITLE
Página de conte-nos um pouco mais

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#30]
**Describe the feature**
Desenvolvimento da seção "Conte-nos um pouco mais do seu animal" no perfil do PetDex, incluindo a criação de cards e uma tabela dinâmica.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar a seção que solicita informações adicionais sobre o pet no aplicativo PetDex. A seção incluirá cards interativos com checkboxes e campos de input, bem como uma tabela dinâmica para a entrada de dados de vacinas.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  A seção será usada para coletar dados valiosos sobre o pet, melhorando a personalização da experiência do usuário e a eficácia das recomendações fornecidas pelo PetDex.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
  A implementação deve reutilizar os componentes de checkbox e campos de input existentes. Os ícones devem ser baixados em formato SVG. A tabela de vacinas deve permitir a inserção dinâmica de informações pelo usuário.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
  Referência visual disponível no Figma: Layout PetDex. A implementação deve seguir o design proposto, mantendo a consistência com o estilo da aplicação.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  A implementação dessa seção deve considerar a acessibilidade e usabilidade, garantindo que seja fácil para todos os usuários inserirem as informações do seu pet.
</details>

**Perguntas Pendentes**
- Os componentes de checkbox e input já estão finalizados e prontos para integração?
- Existem diretrizes específicas para a animação dos cards interativos?
- Como deve ser tratada a entrada de dados na tabela de vacinas e quais validações são necessárias?

**Recomendações**
- Conferir com a equipe de design sobre o estado de erro dos componentes de checkbox e input, caso ainda não estejam definidos.
- Garantir que a tabela dinâmica seja testada em diferentes dispositivos para assegurar a responsividade.

**Comment by hxsggsz** [comment]
eu quero!!!

**Comment by hxsggsz** [comment]
eu quero!!!

**Comment by Alecell** [comment]
Ponto: 13

**Comment by geisabitt** [comment]
Eu quero!!!
