### ISSUE TITLE
Recuperar um componente perdido de um commit

### ISSUE THREAD

**Issue by juliaam** [devhatt/pet-dex-frontend#305]
**Describe the feature**

Inserção do componente de página pet register na aplicação 

<details open>
  <summary>
    <b>Description</b>
  </summary>

Necessário que recupere o componente de PetRegister e suas dependências que foram perdidos desse pr: https://github.com/devhatt/pet-dex-frontend/pull/190/files
e colocar no projeto
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Não é necessário criar nada! Tudo já está feito, apenas pegar o perdido e colocar no projeto.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/user-attachments/assets/0dd54ada-4085-4e8c-8630-6f0bba7c4990)

</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/devhatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/devhatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/devhatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
