### ISSUE TITLE
Font mixins

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#36]
**Describe the feature**
Criação de um arquivo SCSS de definições de fontes para o projeto.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um arquivo SCSS chamado "fonts" que conterá todas as definições de fontes do projeto, utilizando os recursos do SASS para criar mixins e funções reutilizáveis. Esse arquivo deve incluir estilos padronizados para 'font-family: button', 'font-family: text', e outras categorias relevantes, permitindo uma aplicação consistente e eficiente dos estilos de fonte em todo o projeto.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O arquivo "fonts.scss" centralizará a gestão das fontes, facilitando a manutenção e promovendo a consistência visual. Será uma referência rápida para os desenvolvedores aplicarem estilos de texto, garantindo que todos os componentes do projeto sigam o mesmo padrão de design tipográfico.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O arquivo "fonts.scss" deve ser criado dentro da estrutura de diretórios do SASS do projeto. Deve incluir variáveis para fontes primárias e secundárias, pesos, tamanhos e estilos. Utilize mixins e funções do SASS para criar estilos facilmente aplicáveis e modulares. Garanta que o arquivo esteja bem comentado, explicando a finalidade de cada seção e como os desenvolvedores devem utilizar as definições.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Certifique-se de que o arquivo "fonts.scss" esteja integrado com o restante da base de código SCSS do projeto. Forneça instruções claras sobre como outros desenvolvedores podem contribuir para o arquivo e manter a consistência e organização à medida que o projeto evolui.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
Eu quero!!!
