### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#37]
**Describe the feature**
Integração de favicons personalizados na página inicial do projeto utilizando HTML puro.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Criar e implementar favicons para o site usando um gerador de favicon. Esta tarefa envolve selecionar ou criar a imagem apropriada, utilizar um serviço online para gerar os diferentes formatos de favicon necessários e atualizar o código HTML da página inicial para referenciar corretamente esses ícones. Além disso, é preciso garantir a compatibilidade com diversos dispositivos atualizando o arquivo manifest.json com os ícones apropriados.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Favicons são elementos críticos na identificação visual de um site nas abas do navegador e na tela inicial de dispositivos móveis. Eles ajudam os usuários a localizar rapidamente o site desejado entre várias abas abertas e a reconhecer o atalho do site em seus dispositivos. Um conjunto completo e bem implementado de favicons melhora a experiência do usuário e reforça a identidade visual do site.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Selecionar uma imagem representativa para ser o ícone do site e usar um gerador de favicon online para criar os vários tamanhos e formatos necessários. Atualize o HTML da página inicial com as tags `<link>` apropriadas no cabeçalho para apontar para os arquivos de favicon. Assegure-se também de que o arquivo manifest.json está atualizado para refletir os ícones e caminhos corretos, garantindo assim a compatibilidade e funcionalidade em dispositivos móveis e desktops. Teste a implementação em vários navegadores e dispositivos para garantir que os ícones apareçam conforme esperado.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Se possível, inclua exemplos visuais dos favicons em diferentes contextos, como na barra de endereços do navegador, na lista de abas abertas, e como ícones de aplicativos em uma tela de dispositivo móvel. Isso pode ajudar a visualizar como os favicons devem aparecer em diferentes plataformas.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Forneça orientações sobre como escolher a imagem correta para o favicon, recursos para gerar os ícones e instruções detalhadas sobre como testar sua implementação. Inclua qualquer outra informação que possa ser útil para quem está realizando a tarefa, como dicas de melhores práticas ou links para documentação relevante.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by GabrielBruno7** [comment]
Eu quero !!!

**Comment by Frompaje** [comment]
Eu quero!!!

**Comment by jeressy** [comment]
eu quero!!!
