### ISSUE TITLE
Arquivo de cores

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#38]
**Describe the feature**
Criação e implementação de um arquivo SCSS para gerenciamento de cores do projeto.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um arquivo SCSS chamado "colors.scss", que conterá todas as definições de cores do projeto. Esse arquivo deve ser estruturado de maneira a definir cores padrão como 'primary', 'secondary', 'background', 'text', e outras conforme necessário, com base nas cores presentes no layout do projeto. O objetivo é centralizar as definições de cores para facilitar a manutenção e garantir consistência visual em todo o projeto.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Ter um arquivo "colors.scss" centralizado ajuda a manter a consistência das cores em todo o projeto, facilita atualizações e alterações no esquema de cores e torna o processo de desenvolvimento mais eficiente. Os desenvolvedores podem referenciar rapidamente as variáveis de cor ao estilizar componentes, garantindo que todos os elementos sigam o guia de estilo definido.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O arquivo "colors.scss" deve ser criado dentro da estrutura de diretórios SCSS do projeto. Declare variáveis para cada cor principal usada no layout, nomeando-as de forma intuitiva e padronizada (por exemplo, $color-primary, $color-secondary, etc.). Inclua comentários explicativos para descrever cada cor e onde ela deve ser aplicada. Garanta que o arquivo seja importado corretamente nos arquivos SCSS principais para que as variáveis de cor estejam acessíveis em todo o projeto.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Inclua uma amostra visual do paleta de cores no arquivo ou na documentação relacionada para fornecer uma referência rápida das cores definidas. Isso pode ser uma simples grade de cores com nomes de variáveis correspondentes ou capturas de tela do layout com anotações sobre quais cores correspondem a quais variáveis.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Forneça orientações sobre como adicionar ou modificar cores no futuro, mantendo a organização e a padronização do arquivo. Inclua também qualquer convenção de nomenclatura ou prática recomendada que os desenvolvedores devem seguir ao trabalhar com o arquivo "colors.scss".
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by GabrielBruno7** [comment]
Eu quero!!!

**Comment by JpBurgarelli** [comment]
Eu quero!!!

**Comment by PabloSantos-CG** [comment]
Eu quero!

**Comment by JonySamarelli** [comment]
@PabloSantos-CG, beleza? você tá fazendo essa tarefa? Na última daily o Alecell disse pra eu pegar ela mas se tu tiver fazendo de boas

**Comment by PabloSantos-CG** [comment]
@JonySamarelli então de boa man, pode pegar tem nada  não

**Comment by JonySamarelli** [comment]
Eu quero!!!

**Comment by ViniFerreiraL** [comment]
@JpBurgarelli Ale pediu pra perguntar como esta a andança da tesk?

**Comment by JonasGz** [comment]
eu quero!!!

**Comment by JonasGz** [comment]
Eu quero!!!
