### ISSUE TITLE
Integração de Ferramenta de Visualização de Componentes com Vite

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#44]
**Describe the feature**
Criação de uma ferramenta de visualização de componentes adaptada à arquitetura Vite do nosso projeto frontend.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar uma ferramenta como Ladle ou Storybook, que se integre harmoniosamente com o Vite, nosso empacotador de módulos, para facilitar a visualização e o teste dos componentes JavaScript, HTML e SCSS do projeto.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Facilitar o desenvolvimento, teste e documentação dos componentes de UI, proporcionando uma visão clara do comportamento e da aparência de cada componente isoladamente.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Avaliar as ferramentas existentes como Ladle e Storybook para adaptação com Vite, considerar a criação de uma configuração personalizada se necessário para suporte otimizado.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Não aplicável.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
É crucial que a solução escolhida seja compatível com nossa stack atual e possa ser integrada sem problemas significativos de desempenho ou compatibilidade.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by diogocaronte** [comment]
Eu quero!!!
