### ISSUE TITLE
Componente Drop Down

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#47]
**Describe the feature**
Desenvolvimento de um componente de seleção (dropdown) personalizado alinhado ao design do PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar um componente dropdown seguindo as especificações de design fornecidas, que deverá receber uma lista de opções e emitir um evento ao mudar a seleção.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  O componente será utilizado para seleções de opções em formulários, melhorando a experiência do usuário e mantendo a consistência visual do projeto.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
  Utilizar JavaScript, HTML e SCSS para criar um componente funcional que seja adaptável e reutilizável em diferentes partes da aplicação.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
  O layout visual está disponível no Figma para referência na implementação do estilo do componente.

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/682d8884-8ec0-4975-b7e7-79ce2e673901)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  Considerar a acessibilidade e a usabilidade durante a implementação, garantindo que o componente seja navegável via teclado e leitores de tela.
</details>

Perguntas Pendentes:
- Existem estados adicionais do componente (por exemplo, erro, desabilitado) que precisam ser considerados?

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Marcelovmendes** [comment]
Eu quero!

**Comment by DominMFD** [comment]
Eu quero!!!
