### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#5]
Nosso projeto iniciou agora e precisamos de um README explicando um pouco mais sobre o projeto e coisas afim use [o README do octopost](https://github.com/hatcoders/octopost/blob/master/README.md) como referência.

**Comment by RafaelLimaC** [comment]
Eu quero!!!

**Comment by Alecell** [comment]
@aalmeida00 pq eu reabri isso e vc ta assignado nisso? Lembra de algo
