### ISSUE TITLE
Script para configurar vscode corretamente pro projeto

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/pet-dex-frontend#63]
**Describe the feature**
Um script em bash para configurar corretamente o vscode, ao invés de comitar o .vscode e poluir o github do projeto

<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
Eu quero!!!
