### ISSUE TITLE
Melhora do componente de botão

### ISSUE THREAD

**Issue by diogocaronte** [devhatt/pet-dex-frontend#65]
**Describe the feature**
Melhorar o component de botão, permitir desabilita-lo e adicionar identidade visual de acordo com os estados (ex: hover, disable)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by diogocaronte** [comment]
Eu quero!!!

**Comment by Frompaje** [comment]
Eu quero!!!
