### ISSUE TITLE
Criação do componente de toggle

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#71]
**Describe the feature**
O componente de toggle é um switch para ativo e desativo.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 
  O componente de toggle é como um checkbox. Seguir as diretrizes do layout e do material design. https://m3.material.io/components/switch/overview

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Eu como dev, preciso de um componente que me habilite um evento de ativação e desativação de funcionalidades. Esse componente deve ser visual.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O componente deve emitir os eventos de ativo e desativado para serem escutados externamente ao componente.

Icones **não** devem ser suportados.

A "bolinha" deve animar de um lado para o outro e não apenas mudar bruscamente como um "teleporte".

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![Captura de tela 2024-02-05 155013](https://github.com/devhatt/pet-dex-frontend/assets/13935760/42293618-5d61-4c68-8f26-e0a4e436155d)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by nathalia-84** [comment]
Eu quero!!!
