### ISSUE TITLE
Criação de módulo dos breakpoints

### ISSUE THREAD

**Issue by JonasGz** [devhatt/pet-dex-frontend#87]
**Describe the feature**
Criar módulo dos breakpoints existentes.

<details open>
  <summary>
    <b>Description</b>
  </summary>
O objetivo consiste em desenvolver um módulo dos breakpoints, utilizando como referência os breakpoints já definidos em Sass.
</details>

<br>

<details open> 
  <summary>
    <b>Use Case</b>
  </summary>
  
A finalidade desta tarefa é de tornar possível a utilização dos breakpoints nas lógicas do projeto.
</details>

<br>

<details open> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Os breakpoints definidos estão disponíveis na pasta styles/breakpoints.scss, dentro do projeto.
As informações completas dos breakpoints podem ser visualizadas no pull request da task de [criação de breakpoints](https://github.com/devhatt/pet-dex-frontend/pull/74), neste [link](https://github.com/devhatt/pet-dex-frontend/pull/74).

Em caso de dúvidas, procure o @Alecell ou pergunte durante as dailys.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
