### ISSUE TITLE
Criação de componente de slider

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/pet-dex-frontend#92]
**Describe the feature**
Criação de um componente de slider para navegação entre diferentes conteúdos no PetDex.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Desenvolver um componente slider que permita ao usuário navegar entre diferentes conteúdos. O componente deve ser capaz de deslizar para trás arrastando e expor métodos `next()` e `prev()` para a navegação programática. Deve haver eventos que informem o slide atual sempre que a navegação ocorrer.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O slider será utilizado em diversas partes do PetDex para permitir uma navegação intuitiva e direta entre conteúdos relacionados, como seleção de categorias de pets, galerias de imagens, entre outros.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

O slider deve ser implementado com a funcionalidade de touch para dispositivos móveis e opções de controle programático. Deve também permitir a personalização dos slides adjacentes e do slide atual de maneira fácil e acessível.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Embora não haja uma representação visual do componente de slider em ação, o layout atual pode ser visualizado no Figma: [Layout PetDex](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design).

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/8916cdcc-2bc1-48f8-90ed-d3086bf9b6a5)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Deve-se assegurar que o componente seja responsivo e acessível, seguindo as diretrizes de ARIA para componentes de slider.
</details>

**Perguntas Pendentes:**
- Como os itens adjacentes devem ser editados? Existe alguma diretriz de estilo ou funcionalidade específica para isso?
- Existe algum requisito específico para a animação entre os slides, ou isso deve ser definido em colaboração com a equipe de design?

**Recomendações:**
- Considerar a implementação de testes automatizados para garantir a funcionalidade do slider em diferentes cenários de uso.
- Documentar como os eventos de `next()` e `prev()` podem ser acessados e utilizados por outros componentes ou páginas.
- Avaliar a utilização de bibliotecas existentes para a funcionalidade de slider ou a necessidade de desenvolver uma solução personalizada.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
