### ISSUE TITLE
Criação de tela de cadastro de raça do pet 

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/pet-dex-frontend#93]
**Describe the feature**
Criação de tela de cadastro da etapa dois do cadastro de pets 

<details open>
  <summary>
    <b>Description</b>
  </summary>
  
Criar a tela usando componentes já feitos na aplicação e criando novos dependendo da demanda de utilização 
</details>

<br>

<details open> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Quem pegar essa task vai ter que criar essa tela como um componente e se certificar de usar todos os componentes que foram feitos para compor ela.

Componentes já feitos que devem ser usados: 

- [ ] #20 
- [ ] #95 

</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

**ATENÇÃO, A PARTE QUE DEVE SER FEITA É APENAS O QUE ESTÁ NA IMAGEM ABAIXO**

![image](https://github.com/devhatt/pet-dex-frontend/assets/69992923/2c195e98-d85f-48fa-9870-2257c9d87459)

</details>

<br>

<details open> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Use o [figma](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&node-id=107%3A5&mode=design&t=TskAdP6lYiCmxJMR-1) para se basear nos componentes
</details>

**Comment by JonySamarelli** [comment]
Eu quero!!!

**Comment by muritadb** [comment]
Eu quero!!!
