### ISSUE TITLE
Tela de nome de bichinho

### ISSUE THREAD

**Issue by Alecell** [devhatt/pet-dex-frontend#96]
**Describe the feature**
Desenvolvimento da tela de nome de bichinho. Essa tela possui o componente já existente de seleção de imagem, o componente já existente de input e tambem o já existente de botão tambem.

<details open>
  <summary>
    <b>Description</b>
  </summary>

Esta é uma das telas do fluxo de cadastrar pet. O uso dela é, adicionar a imagem, adicionar o nome e então clicar em **continuar** pra seguir para a proxima etapa.

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
Esta tela será criada como um componente isolado, usando outros componentes, para que eventualmente seja usada no fluxo de adição de pet.

**Essa tela tem algumas restrições:**
- Não é possivel clicar no botão de **continuar** caso não tenha uma imagem selecionada
- Não é possivel clicar no botão de **continuar** caso não tenha o nome do pet

_É preciso falar com o designer pra saber qual o formato do erro de quando não tem imagem ou nome_

Esse componente deve emitir o nome do pet e sua imagem quando elas forem definidas.

**Atente-se que os componentes da tela devem retornar o dado atualizado através de um evento de emitter para o componente pai.**

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>
Figma: https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&node-id=107-5&mode=design&t=q6D9l7qTzBMaJ5eD-0

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/34745670-665a-4a2b-9e36-28fafe3af151)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se que esté componente **não compoem** a parte superior da progress bar amarela, nem todo o resto que fica a cima da seleção da imagem. 

**Está parte a baixo não faz parte do componente**
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/6c40adce-e447-428a-baa1-984d858bad7b)

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by MateusHenriquegringo** [comment]
EU QUERO !!!

**Comment by MateusHenriquegringo** [comment]
EU QUERO!!!

**Comment by ClaudioBioni** [comment]
alô alô, ta comigo! sou o shoT
