### ISSUE TITLE
Criação da tela de inserção de peso do pet

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/pet-dex-frontend#97]
**Describe the feature**
Criação de tela de cadastro da etapa cinco do cadastro de pets 

<details open>
  <summary>
    <b>Description</b>
  </summary>
  
Criar a tela usando componentes já feitos na aplicação e criando o que for necessário 
</details>

<br>

<details open> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Quem pegar essa task vai ter que criar essa tela como um componente e se certificar de usar todos os componentes que foram feitos para compor ela.

Quando o valor for inserido no campo de texto ele deve atualizar o valor do range e se mudar o checkbox radius ele deve mudar lá tmb

Componentes já feitos que devem ser usados: 
- [ ] #24 
- [ ] #26 

</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

**ATENÇÃO, A PARTE QUE DEVE SER FEITA É APENAS O QUE ESTÁ NA IMAGEM ABAIXO**

![image](https://github.com/devhatt/pet-dex-frontend/assets/69992923/968b08be-3b12-4d2a-a62d-c46341cb6571)

</details>

<br>

<details open> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Use o [figma](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&node-id=107%3A5&mode=design&t=TskAdP6lYiCmxJMR-1) para se basear nos componentes
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by marceana** [comment]
eu quero!!!
