### ISSUE TITLE
Fixes ProgressBar Component test

### ISSUE THREAD

**Issue by JonySamarelli** [devhatt/pet-dex-frontend#98]
**Describe the bug**
ProgressBar was updated and the test file is outdated

<details open> 
  <summary>
    <b>Description</b>
  </summary>
Fixes the ProgressBar test file
</details>

<br>

<details> 
  <summary>
    <b>Steps to Reproduce</b>
  </summary>

run pnpm test

</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>
ProgressBar test succeed
</details>

<br>

<details> 
  <summary>
    <b>Current Behavior</b>
  </summary>
ProgressBar test breaks
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by JonySamarelli** [comment]
Eu quero!!!
